### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mady143** [umair13adil/tensorflow_lite_flutter#1]
Hi @umair13adil ,
I am new to flutter and working lo tflite andi prepared a app with detecting a leaf image through camera and gallery and i had converted the hdf5 model to tflite and using that tflite model with some label while testing/predicting the image i am getting an error like

Exception has occurred. PlatformException (PlatformException(error, Unsupported value: java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 38] and a Java object with shape [1, 40]., null)) in flutter
Coulod any one help me

Thanks and Regards,
Manikantha Sekhar.

**Comment by umair13adil** [comment]
@mady143 This means that the input that you are sending to the TensorFlow does not match the model's input. Please check your hdf5 model's summary to get details about the input shape.

**Comment by mmusunur** [comment]
Hi @umair13adil 
I had resolved the issue by replacing the labels.txt file so its working fine
